#!/bin/bash
# Database Initialization Script for ROTA Production

echo "🚀 ROTA Database Initialization"
echo "================================"
echo ""
echo "This script creates all database tables for ROTA production."
echo ""
echo "Prerequisites:"
echo "  - Railway CLI installed: npm install -g @railway/cli"
echo "  - Authenticated: railway login"
echo "  - Linked to project: railway link"
echo ""
echo "Execute these commands in order:"
echo ""
echo "1. Authenticate with Railway:"
echo "   railway login"
echo ""
echo "2. Link to the project:"
echo "   railway link"
echo "   (Select: rotainteligente project)"
echo "   (Select: rotainteligente service)"
echo ""
echo "3. Create database tables:"
echo "   railway run npx prisma db push --accept-data-loss"
echo ""
echo "4. Verify tables were created:"
echo "   railway run npx prisma db execute --stdin < /dev/null"
echo ""
echo "5. Redeploy to run seed:"
echo "   railway redeploy"
echo ""
echo "After these steps, the application will be fully operational."
echo "================================"
