import { Project, AlertType, Edital } from "./types";

export const B = {
  tealDark: "#0A6475",
  teal: "#1A7C7E",
  tealLight: "#E6F4F5",
  amber: "#E8A020",
  amberLight: "#FEF3DC",
  navy: "#1E3B5C",
  white: "#FFFFFF",
  offWhite: "#F8FAFB",
  gray: "#6B7280",
  grayLight: "#F1F5F9",
  grayBorder: "#D1D5DB",
  green: "#059669",
  greenBg: "#ECFDF5",
  blue: "#0369A1",
  blueBg: "#EFF6FF",
  purple: "#7C3AED",
  purpleBg: "#F5F3FF",
  red: "#DC2626",
  redBg: "#FEF2F2",
  orange: "#D97706",
  orangeBg: "#FFFBEB",
  charcoal: "#374151",
};

export const EDITAIS: Edital[] = [
  {
    id: "ED-2026-001",
    nome: "Chamamento Público COMDICA 2026",
    financiador: "Prefeitura do Recife / COMDICA",
    valorMax: 400000,
    prazo: "2026-05-15",
    status: "Aberto",
    aderencia: 5,
    categoria: "Fundo Municipal",
    linha: "Eixo I — Proteção Básica",
    porte: "Grande",
    link: "https://recife.pe.gov.br/comdica",
    observacao: "Edital recorrente. IGS tem histórico de 100% de aprovação neste financiador."
  },
  {
    id: "ED-2026-002",
    nome: "Edital Tecendo Infâncias",
    financiador: "Fundação Maria Cecilia Souto Vidigal",
    valorMax: 150000,
    prazo: "2026-04-24",
    status: "Aberto",
    aderencia: 4,
    categoria: "Fundação Privada",
    linha: "Primeira Infância",
    porte: "Pequeno",
    link: "https://fmcsv.org.br",
    observacao: "Exige vídeo de apresentação e portfólio detalhado."
  },
  {
    id: "ED-2026-003",
    nome: "BrazilFoundation — Ciclo 2026",
    financiador: "BrazilFoundation",
    valorMax: 100000,
    prazo: "2026-06-30",
    status: "Em análise",
    aderencia: 3,
    categoria: "Cooperação Internacional",
    linha: "Educação e Cidadania",
    porte: "Médio",
    observacao: "Aguardando publicação do guia do proponente."
  },
  {
    id: "ED-2026-004",
    nome: "Edital Itaú Social — Unicef",
    financiador: "Itaú Social",
    valorMax: 250000,
    prazo: "2026-04-10",
    status: "Encerrado",
    aderencia: 5,
    categoria: "Instituto Privado",
    linha: "Educação Integral",
    porte: "Médio",
    observacao: "IGS não submeteu este ano por conflito de agenda com COMDICA."
  }
];

export const PROJECTS: Project[] = [
  {
    id: "ROTA-2026-001",
    nome: "Guia Digital Teen",
    edital: "FMCA/COMDICA",
    financiador: "Fundo Municipal da Criança",
    area: "Digital",
    valor: 320000,
    status: "Inscrito",
    prazo: "2026-04-15",
    responsavel: "Viviane Castro",
    probabilidade: 72,
    risco: "Médio",
    aderencia: 5,
    territorio: "RPA 6 — Pina / Ipsep",
    publico: "Adolescentes 12–18 anos",
    competitividade: "Alta",
    proximoPasso: "Aguardar resultado do edital",
    ptScore: 8.1,
    ptCriterios: [
      { critério: "Aderência", score: 9 },
      { critério: "Força Conceitual", score: 8 },
      { critério: "Adequação Financiador", score: 9 },
      { critério: "Cap. Institucional", score: 8 },
      { critério: "Maturidade", score: 7 },
      { critério: "Competitividade", score: 7 },
      { critério: "Plausibilidade Orçam.", score: 8 },
      { critério: "Risco Doc.", score: 9 },
    ],
    historico: [
      { data: "10/02/2026", acao: "Oportunidade identificada", autor: "Janaina Constantino" },
      { data: "14/02/2026", acao: "Triagem aprovada — score 5/5", autor: "Viviane Castro" },
      { data: "18/02/2026", acao: "Elaboração iniciada", autor: "Vânia Rodrigues" },
      { data: "05/03/2026", acao: "Revisão técnica concluída", autor: "Rodrigo Nery" },
      { data: "12/03/2026", acao: "Submetido — protocolo #2026-0312-IGS", autor: "Viviane Castro" },
    ],
    changeLog: [
      { id: "cl1", data: "12/03/2026", autor: "Viviane Castro", campo: "status", valorAnterior: "Revisão", valorNovo: "Inscrito", justificativa: "Submissão oficial realizada no portal do COMDICA." },
      { id: "cl2", data: "05/03/2026", autor: "Rodrigo Nery", campo: "probabilidade", valorAnterior: 65, valorNovo: 72, justificativa: "Revisão técnica elevou a qualidade da proposta." },
      { id: "cl3", data: "20/02/2026", autor: "Vânia Rodrigues", campo: "valor", valorAnterior: 300000, valorNovo: 320000, justificativa: "Ajuste no valor de equipamentos após cotação atualizada." },
    ],
    docs: [
      { id: "doc-1", nome: "Estatuto Social", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "doc-2", nome: "CNPJ", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "doc-3", nome: "CND Federal", status: "Aprovado", validade: "2026-05-20", obrigatorio: true, versao: 1 },
      { id: "doc-4", nome: "CND Trabalhista", status: "Aprovado", validade: "2026-06-10", obrigatorio: true, versao: 1 },
      { id: "doc-5", nome: "Plano de Trabalho", status: "Aprovado", validade: null, obrigatorio: true, versao: 2 },
      { id: "doc-6", nome: "Orçamento Detalhado", status: "Aprovado", validade: null, obrigatorio: true, versao: 2 },
    ],
    metas: [
      { id: "m1", descricao: "Certificar jovens em tecnologia", indicador: "Jovens certificados", meta: 500, alcancado: 380, unidade: "Jovens" },
      { id: "m2", descricao: "Inserção no mercado de trabalho", indicador: "Jovens empregados", meta: 50, alcancado: 12, unidade: "Jovens" },
    ],
    etapas: [
      { id: "e1", nome: "Mobilização", inicio: "2026-01-01", fim: "2026-02-28", status: "Concluído", peso: 20 },
      { id: "e2", nome: "Execução das Aulas", inicio: "2026-03-01", fim: "2026-07-31", status: "Em curso", peso: 60 },
    ],
    expenses: [
      { 
        id: "exp1", descricao: "Compra de Notebooks", valor: 45000, data: "2026-03-15", categoria: "Equipamentos", status: "Validado", 
        vincMetaId: "m1", vincEtapaId: "e2", 
        cotacoes: [
          { id: "c1", fornecedor: "Dell", valor: 45000, data: "2026-03-10", vencedora: true },
          { id: "c2", fornecedor: "HP", valor: 48000, data: "2026-03-11", vencedora: false },
        ]
      },
      { 
        id: "exp2", descricao: "Coffee Break Evento", valor: 1200, data: "2026-03-20", categoria: "Serviços", status: "Glosa", 
        justificativa: "Valor acima do teto do edital para alimentação sem justificativa prévia.",
        vincMetaId: "m1", vincEtapaId: "e1", 
        cotacoes: []
      }
    ],
    complianceChecks: [
      { id: "cc1", item: "Vínculo com Meta/Etapa", status: "Conforme", data: "2026-03-20" },
      { id: "cc2", item: "Documentação Comprobatória", status: "Conforme", data: "2026-03-20" },
      { id: "cc3", item: "Economicidade (Cotações)", status: "Conforme", data: "2026-03-20" },
      { id: "cc4", item: "Regularidade Fiscal", status: "Conforme", data: "2026-03-20" },
    ],
    auditLogs: [
      { id: "al1", data: "2026-03-20 14:30", usuario: "Rodrigo Nery", acao: "Validação de Despesa", entidade: "Expense", entidadeId: "exp1", detalhes: "Aprovado após conferência de NF e Cotações." },
      { id: "al2", data: "2026-03-12 10:00", usuario: "Viviane Castro", acao: "Submissão de Projeto", entidade: "Project", entidadeId: "p1", detalhes: "Projeto submetido ao portal COMDICA." },
    ],
    scoreCompliance: 92,
    scoreRiscoGlosa: 15,
    observacao: "Projeto com alto alinhamento ao histórico de aprovações da COMDICA. Referência: Guia Digital 2024 (aprovado, R$280k). Equipe já mobilizada.",
    ano: 2026,
    categoriaEdital: "Fundo Municipal",
    programaInterno: "Inclusão Digital"
  },
  {
    id: "ROTA-2026-002",
    nome: "Primeiros Laços",
    edital: "Edital Tecendo Infâncias",
    financiador: "Prosas/Financiador Privado",
    area: "Primeira Infância",
    valor: 80000,
    status: "Elaboração",
    prazo: "2026-04-24",
    responsavel: "Lara Patrícia",
    probabilidade: 61,
    risco: "Médio",
    aderencia: 4,
    territorio: "Ipsep / Imbiribeira",
    publico: "Crianças 0–6 anos e famílias",
    competitividade: "Alta",
    proximoPasso: "Viviane gravar vídeo YouTube; confirmar orçamento anual IGS",
    ptScore: 7.2,
    ptCriterios: [
      { critério: "Aderência", score: 8 },
      { critério: "Força Conceitual", score: 7 },
      { critério: "Adequação Financiador", score: 7 },
      { critério: "Cap. Institucional", score: 8 },
      { critério: "Maturidade", score: 6 },
      { critério: "Competitividade", score: 6 },
      { critério: "Plausibilidade Orçam.", score: 8 },
      { critério: "Risco Doc.", score: 8 },
    ],
    historico: [
      { data: "15/03/2026", acao: "Oportunidade identificada no Prosas", autor: "Janaina Constantino" },
      { data: "18/03/2026", acao: "Triagem aprovada", autor: "Viviane Castro" },
      { data: "22/03/2026", acao: "Elaboração iniciada", autor: "Lara Patrícia" },
    ],
    docs: [
      { id: "d2-1", nome: "Estatuto Social", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d2-2", nome: "CNPJ", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d2-3", nome: "CND Municipal Recife", status: "A Vencer", validade: "2026-04-18", obrigatorio: true, versao: 1 },
      { id: "d2-4", nome: "Portfólio Institucional", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d2-5", nome: "Vídeo YouTube (exigência)", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
      { id: "d2-6", nome: "Orçamento Anual IGS", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
    ],
    observacao: "Prazo: 24/abr. Ações pendentes críticas: vídeo da Viviane e confirmação do orçamento anual. CND Municipal vence antes do prazo — renovar urgente.",
    ano: 2026,
    categoriaEdital: "Fundação Privada",
    programaInterno: "Primeira Infância"
  },
  {
    id: "ROTA-2026-003",
    nome: "Programa Meu Passo",
    edital: "FMCA/COMDICA — Eixo III/TEA",
    financiador: "Fundo Municipal da Criança",
    area: "Saúde Mental / TEA",
    valor: 700000,
    status: "Inscrito",
    prazo: "2026-05-10",
    responsavel: "Rodrigo Nery",
    probabilidade: 65,
    risco: "Baixo",
    aderencia: 5,
    territorio: "RPA 6 — múltiplos bairros",
    publico: "30 crianças TEA",
    competitividade: "Média",
    proximoPasso: "Aguardar resultado — preparar equipe de execução antecipadamente",
    ptScore: 8.4,
    ptCriterios: [
      { critério: "Aderência", score: 9 },
      { critério: "Força Conceitual", score: 9 },
      { critério: "Adequação Financiador", score: 8 },
      { critério: "Cap. Institucional", score: 8 },
      { critério: "Maturidade", score: 8 },
      { critério: "Competitividade", score: 7 },
      { critério: "Plausibilidade Orçam.", score: 9 },
      { critério: "Risco Doc.", score: 9 },
    ],
    historico: [
      { data: "01/02/2026", acao: "Oportunidade identificada", autor: "Viviane Castro" },
      { data: "05/02/2026", acao: "Triagem aprovada — prioridade máxima", autor: "Viviane Castro" },
      { data: "10/02/2026", acao: "Elaboração iniciada com Rodrigo Nery", autor: "Viviane Castro" },
      { data: "25/02/2026", acao: "Revisão concluída", autor: "Viviane Castro" },
      { data: "28/02/2026", acao: "Submetido", autor: "Rodrigo Nery" },
    ],
    docs: [
      { id: "d3-1", nome: "Estatuto Social", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d3-2", nome: "CND Federal", status: "Aprovado", validade: "2026-07-01", obrigatorio: true, versao: 1 },
      { id: "d3-3", nome: "Plano de Trabalho 24 meses", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d3-4", nome: "Orçamento Detalhado", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
    ],
    observacao: "Projeto de maior valor no pipeline atual. Equipe técnica (Rodrigo Nery + 2 psicólogos) pré-identificada. Alta chance de aprovação dado histórico com COMDICA.",
    ano: 2026,
    categoriaEdital: "Fundo Municipal",
    programaInterno: "Saúde Mental"
  },
  {
    id: "ROTA-2026-007",
    nome: "Guia Digital — Cidadania +60",
    edital: "COMDIR/Recife",
    financiador: "Conselho de Direitos do Idoso",
    area: "Digital / Idosos",
    valor: 110000,
    status: "Aprovado",
    prazo: "2026-04-30",
    responsavel: "Viviane Castro",
    probabilidade: 100,
    risco: "Baixo",
    aderencia: 5,
    territorio: "RPA 6",
    publico: "Idosos 60+",
    competitividade: "-",
    proximoPasso: "Aguardar publicação da portaria — iniciar formalização do convênio",
    ptScore: 9.0,
    ptCriterios: [
      { critério: "Aderência", score: 10 },
      { critério: "Força Conceitual", score: 9 },
      { critério: "Adequação Financiador", score: 9 },
      { critério: "Cap. Institucional", score: 9 },
      { critério: "Maturidade", score: 9 },
      { critério: "Competitividade", score: 8 },
      { critério: "Plausibilidade Orçam.", score: 9 },
      { critério: "Risco Doc.", score: 9 },
    ],
    historico: [
      { data: "15/01/2026", acao: "Inscrito no COMDIR", autor: "Viviane Castro" },
      { data: "10/03/2026", acao: "Aprovado — resultado publicado", autor: "Viviane Castro" },
      { data: "15/03/2026", acao: "Aguardando portaria de aprovação", autor: "Alice Thorpe" },
    ],
    docs: [
      { id: "d7-1", nome: "Portaria de Aprovação", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
      { id: "d7-2", nome: "Minuta do Convênio", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
      { id: "d7-3", nome: "Documentação institucional", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
    ],
    observacao: "Aprovado. Valor: R$110.000. Aguardar publicação da portaria para iniciar processo de formalização. Prazo de formalização: 30 dias após publicação.",
    ano: 2026,
    categoriaEdital: "Conselho de Direitos",
    programaInterno: "Inclusão Digital"
  },
  {
    id: "ROTA-2026-010",
    nome: "Guia Digital (Turma 2024)",
    edital: "Guia Digital — Execução Vigente",
    financiador: "COMPAZ Atriz Lêda Alves",
    area: "Digital",
    valor: 220000,
    status: "Execução",
    prazo: "2026-08-31",
    responsavel: "Vânia Rodrigues",
    probabilidade: 100,
    risco: "Baixo",
    aderencia: 5,
    territorio: "Pina — COMPAZ Atriz Lêda Alves",
    publico: "Jovens 16–29 anos",
    competitividade: "-",
    proximoPasso: "Entrega do relatório parcial — 30/abr/2026. Prestação de contas intermediária.",
    ptScore: 9.5,
    ptCriterios: [
      { critério: "Aderência", score: 10 },
      { critério: "Força Conceitual", score: 10 },
      { critério: "Adequação Financiador", score: 9 },
      { critério: "Cap. Institucional", score: 10 },
      { critério: "Maturidade", score: 9 },
      { critério: "Competitividade", score: 9 },
      { critério: "Plausibilidade Orçam.", score: 9 },
      { critério: "Risco Doc.", score: 9 },
    ],
    historico: [
      { data: "10/01/2024", acao: "Vigência iniciada", autor: "Viviane Castro" },
      { data: "01/07/2024", acao: "Relatório parcial aprovado", autor: "Vânia Rodrigues" },
      { data: "01/01/2025", acao: "Aditivo de prazo aprovado", autor: "Viviane Castro" },
    ],
    docs: [
      { id: "d10-1", nome: "Contrato de Vigência", status: "Aprovado", validade: "2026-08-31", obrigatorio: true, versao: 1 },
      { id: "d10-2", nome: "Relatório Parcial 1", status: "Aprovado", validade: null, obrigatorio: true, versao: 1 },
      { id: "d10-3", nome: "Relatório Parcial 2", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
      { id: "d10-4", nome: "Prestação de Contas Intermediária", status: "Pendente", validade: null, obrigatorio: true, versao: 1 },
    ],
    observacao: "Projeto flagship do IGS. 764 inscritos, 558 certificados, 94 com inserção produtiva documentada. Em execução contínua.",
    ano: 2024,
    categoriaEdital: "Convênio Público",
    programaInterno: "Inclusão Digital",
    vigenciaInicio: "2024-01-10",
    vigenciaFim: "2026-08-31",
    progressoFisico: 75,
    progressoFinanceiro: 68
  },
];

export const ALERTS: AlertType[] = [
  { id: 1, nivel: "N4", tipo: "Prazo de Submissão", projeto: "MARÉ DELAS", prazo: "20/abr/2026", dias: 17, cor: B.red, bgCor: B.redBg },
  { id: 2, nivel: "N4", tipo: "Documento Vencendo", projeto: "Primeiros Laços", prazo: "18/abr/2026", dias: 15, cor: B.red, bgCor: B.redBg, doc: "CND Municipal Recife" },
  { id: 3, nivel: "N3", tipo: "Prazo de Submissão", projeto: "Primeiros Laços", prazo: "24/abr/2026", dias: 21, cor: B.orange, bgCor: B.orangeBg },
  { id: 4, nivel: "N3", tipo: "Documento Pendente", projeto: "Primeiros Laços", prazo: "24/abr/2026", dias: 21, cor: B.orange, bgCor: B.orangeBg, doc: "Vídeo YouTube" },
  { id: 5, nivel: "N3", tipo: "Formalização Aprovado", projeto: "Guia Digital — Cidadania +60", prazo: "30/abr/2026", dias: 27, cor: B.orange, bgCor: B.orangeBg },
  { id: 6, nivel: "N2", tipo: "Prazo de Submissão", projeto: "Guia Digital Teen", prazo: "15/abr/2026", dias: 12, cor: B.blue, bgCor: B.blueBg },
  { id: 7, nivel: "N2", tipo: "Relatório Parcial", projeto: "Guia Digital (Turma 2024)", prazo: "30/abr/2026", dias: 27, cor: B.blue, bgCor: B.blueBg },
  { id: 8, nivel: "N1", tipo: "Resultado Previsto", projeto: "Guia Alimenta Recife", prazo: "Mai/2026", dias: 45, cor: B.gray, bgCor: B.grayLight },
];
